version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - docker build -t $IMAGE_REPO_URI:latest .
  post_build:
    commands:
      - docker push $IMAGE_REPO_URI:latest
